export default {
  items: [
    {
      name: "item1",
      index: 0,
      url: "WeatherApp",
      title: "Weather App",
      lang: "React",
      codeSrc: "https://github.com/amyfranz/weather_app",
      projectSrc: "https://amy-weather-app.netlify.app",
    },
    {
      name: "item2",
      index: 1,
      url: "Movie",
      title: "Movie Finder",
      lang: "React",
      codeSrc: "https://github.com/amyfranz/MovieSearch",
      projectSrc: "https://amy-movie-search.netlify.app",
    },
    {
      name: "item3",
      index: 2,
      url: "Recipe",
      title: "Recipe Search",
      lang: "React",
      codeSrc: "https://github.com/amyfranz/recipe-finder",
      projectSrc: "https://amy-recipe-finder.netlify.app",
    },
    {
      name: "item4",
      index: 3,
      url: "Messenger",
      title: "Messenger",
      lang: "React",
      codeSrc: "https://github.com/amyfranz/Messenger-App-React",
      projectSrc: "https://amy-messanging-app.netlify.app",
    },
    {
      name: "item5",
      index: 4,
      url: "JS30",
      title: "JS 30 Challenge",
      lang: "Java Script",
      codeSrc: "https://github.com/amyfranz/JavaScript30",
      projectSrc: "https://codepen.io/collection/nqVMBL",
    },
    {
      name: "item5",
      index: 5,
      url: "Theatre",
      title: "Theatre Ticket Booking",
      lang: "Rails",
      codeSrc: "https://github.com/Brunosil97/Theatre-Junkie",
      projectSrc: "https://youtu.be/4OqoX8RX3qA",
    },
    {
      name: "item6",
      index: 6,
      url: "Corona",
      title: "Corona Virus Website",
      lang: "Backend: rails, Frontend: Javascript",
      codeSrc: "https://github.com/amyfranz/CoronaVirus",
      projectSrc: "https://youtu.be/XHkrBMy8yf8",
    },
  ],
};
